export const GET_CATEGORY_FETCH='GET_CATEGORY_FETCH';
export const GET_CATEGORY_SUCCESS='GET_CATEGORY_SUCCESS';
export const GET_SUBCATEGORY_FETCH='GET_SUBCATEGORY_FETCH';
export const GET_SUBCATEGORY_SUCCESS='GET_SUBCATEGORY_SUCCESS';
export const GET_MEALTYPE_FETCH='GET_MEALTYPE_FETCH';
export const GET_MEALTYPE_SUCCESS='GET_MEALTYPE_SUCCESS';
export const INITIAL='INITIAL';
export const FETCH_INITIAL_DATA='FETCH_INITIAL_DATA';
export const SET_FETCH_DATA='SET_FETCH_DATA';
export const SET_FETCH_DATA_SUCCESS='SET_FETCH_DATA_SUCCESS';

